export const data = [
  {
    country: "Afghanistan",
    percentage: 0.3,
    content: "Increase in the production of wheat",
    currency: "AFN",
    symbol: "؋",
    rate: 68.4,
    mobileCode: 93,
    countryCode: "AFG",
    price: [
      {
        name: "Wheat",
        price: [398.53, 394.91, 387.66, 371.0],
      },
      {
        name: "Rice",
        price: [1066.61, 993.43, 970.24, 947.78],
      },
      {
        name: "Soybeans",
        price: [978.21, 999.95, 920.24, 913.0],
      },
      {
        name: "Sugar",
        price: [1397.75, 1399.93, 1403.55, 1, 404.27],
      },
    ],
  },
  {
    country: "Algeria",
    percentage: 2,
    content: "Increase in agricultural production",
    currency: "DZD",
    symbol: "دج",
    rate: 132.09,
    mobileCode: 213,
    countryCode: "ALG",
  },
  {
    country: "Angola",
    percentage: 4.2,
    content: "Increase in GDP",
    currency: "AOA",
    symbol: "Kz",
    rate: 951.47,
    mobileCode: 631,
    countryCode: "ANG",
  },
  {
    country: "Argentina",
    percentage: 1.5,
    content: "Increase in agricultural productivity",
    currency: "ARS",
    symbol: "$",
    rate: 969.5,
    mobileCode: 54,
    countryCode: "ARG",
  },
  {
    country: "Australia",
    percentage: 5,
    content: "Decrease in aricultural land",
    currency: "AUD",
    symbol: "$",
    rate: 1.45,
    mobileCode: 61,
    countryCode: "AUL",
  },
  {
    country: "Austria",
    percentage: 4.4,
    content: "Increase in agricultural output",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
    mobileCode: 43,
    countryCode: "AUS",
  },
  {
    country: "Belgium",
    percentage: 8.6,
    content: "Decrease in production value",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
    mobileCode: 32,
    countryCode: "BEL",
  },
  {
    country: "Benin",
    percentage: 56,
    content: "Increase in market goods",
    currency: "XOF",
    symbol: "Fr",
    rate: 591,
    mobileCode: 229,
    countryCode: "BEN",
  },
  {
    country: "Brazil",
    percentage: 3.2,
    content: "Increase in agricultural productivity",
    currency: "BRL",
    symbol: "R$",
    rate: 5.46,
    mobileCode: 55,
    countryCode: "BRA",
  },
  {
    country: "Cameroon",
    percentage: 3.2,
    content: "Increase in production index",
    currency: "XAF",
    symbol: "Fr",
    rate: 598.5,
    mobileCode: 237,
    countryCode: "CMR",
  },
  {
    country: "Canada",
    percentage: 50,
    content: "Decrease in number of farms",
    currency: "CAD",
    symbol: "$",
    rate: 1.36,
    mobileCode: 1,
    countryCode: "CAN",
  },
  {
    country: "China",
    percentage: 1.8,
    content: "Increase in grain production",
    currency: "CNY",
    symbol: "¥",
    rate: 7.02,
    mobileCode: 86,
    countryCode: "CPR",
  },
  {
    country: "Colombia",
    percentage: 52,
    content: "Increase in informal land tenure",
    currency: "COP",
    symbol: "$",
    rate: 4165.64,
    mobileCode: 57,
    countryCode: "COL",
  },
  {
    country: "Egypt",
    percentage: 91,
    content: "Increase in GDP",
    currency: "EGP",
    symbol: "ج.م",
    rate: 48.29,
    mobileCode: 20,
    countryCode: "EGY",
  },
  {
    country: "France",
    percentage: 16,
    content: "Decrease in produce price",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
    mobileCode: 33,
    countryCode: "FRA",
  },
  {
    country: "Germany",
    percentage: 9.2,
    content: "Decrease in economic assessment",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
    mobileCode: 49,
    countryCode: "GER",
  },
  {
    country: "Ghana",
    percentage: 5,
    content: "Decrease in food index",
    currency: "GHS",
    symbol: "₵",
    rate: 15.85,
    mobileCode: 233,
    countryCode: "GHA",
  },
  {
    country: "Hungary",
    percentage: 28,
    content: "Increase in agricultural production",
    currency: "HUF",
    symbol: "Ft",
    rate: 366.17,
    mobileCode: 36,
    countryCode: "HUN",
  },
  {
    country: "India",
    percentage: 3.2,
    content: "Increase in agricultural production",
    currency: "INR",
    symbol: "₹",
    rate: 15480,
    mobileCode: 91,
    countryCode: "IND",
  },
  {
    country: "Indonesia",
    percentage: 2,
    content: "Decrease in agricultural workforce",
    currency: "IDR",
    symbol: "Rp",
    rate: 83.92,
    mobileCode: 62,
    countryCode: "INS",
  },
  {
    country: "Iran",
    percentage: 0.3,
    content: "Increase to the GDP",
    currency: "IRR",
    symbol: "﷼",
    rate: 42000,
    mobileCode: 98,
    countryCode: "IRA",
  },
  {
    country: "Iraq",
    percentage: 50,
    content: "Decrease in crop yield",
    currency: "IQD",
    symbol: "ع.د",
    rate: 1309,
    mobileCode: 964,
    countryCode: "IRQ",
  },
  {
    country: "Israel",
    percentage: 70,
    content: "Decrease in productivity",
    currency: "ILS",
    symbol: "₪",
    rate: 3.81,
    mobileCode: 972,
    countryCode: "ISR",
  },
  {
    country: "Italy",
    percentage: 2.8,
    content: "Increase in agricultural market",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
    mobileCode: 39,
    countryCode: "ITA",
  },
  {
    country: "Japan",
    percentage: 30,
    content: "Decrease in the number of farms",
    currency: "JPY",
    symbol: "¥",
    rate: 148.71,
    mobileCode: 81,
    countryCode: "JPN",
  },
  {
    country: "Kenya",
    percentage: 15,
    content: "Increase in sugarcane production",
    currency: "KES",
    symbol: "Sh",
    rate: 128.5,
    mobileCode: 254,
    countryCode: "KEN",
  },
  {
    country: "Madagascar",
    percentage: 77,
    content: "Increase in rural poverty",
    currency: "MGA",
    symbol: "Ar",
    rate: 4556.46,
    mobileCode: 261,
    countryCode: "MAG",
  },
  {
    country: "Malaysia",
    percentage: 0.1,
    content: "Increase in agricultural sector",
    currency: "MYR",
    symbol: "RM",
    rate: 4.21,
    mobileCode: 60,
    countryCode: "MAL",
  },
  {
    country: "Mexico",
    percentage: 24,
    content: "Decrease in agricultural productivity",
    currency: "MXN",
    symbol: "$",
    rate: 19.15,
    mobileCode: 52,
    countryCode: "MEX",
  },
  {
    country: "Netherlands",
    percentage: 5,
    content: "Increase in agricultural exports",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
    mobileCode: 31,
    countryCode: "NET",
  },
  {
    country: "New Zealand",
    percentage: 91,
    content: "Increase in irrigated land",
    currency: "NZD",
    symbol: "$",
    rate: 1.62,
    mobileCode: 64,
    countryCode: "NZE",
  },
  {
    country: "Niger",
    percentage: 15,
    content: "Increase in agricultural sector",
    currency: "XOF",
    symbol: "Fr",
    rate: 591,
    mobileCode: 227,
    countryCode: "NER",
  },
  {
    country: "Nigeria",
    percentage: 0.2,
    content: "Increase in agricultural sector",
    currency: "NGN",
    symbol: "₦",
    rate: 1600,
    mobileCode: 234,
    countryCode: "NIR",
  },
  {
    country: "Portugal",
    percentage: 4,
    content: "Increase in crop production",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
    mobileCode: 351,
    countryCode: "POR",
  },
  {
    country: "Qatar",
    percentage: 15,
    content: "Decrease in food production",
    currency: "QAR",
    symbol: "ر.ق",
    rate: 3.64,
    mobileCode: 974,
    countryCode: "QAT",
  },
  {
    country: "Russia",
    percentage: 15,
    content: "Increase in agricultural productivity",
    currency: "RUB",
    symbol: "₽",
    rate: 95.25,
    mobileCode: 7,
    countryCode: "RUS",
  },
  {
    country: "Saudi Arabia",
    percentage: 7.8,
    content: "Increase in agricultural sector",
    currency: "SAR",
    symbol: "ر.س",
    rate: 3.76,
    mobileCode: 966,
    countryCode: "SAU",
  },
  {
    country: "Singapore",
    percentage: 10,
    content: "Increase in food production",
    currency: "SGD",
    symbol: "$",
    rate: 1.31,
    mobileCode: 65,
    countryCode: "SIN",
  },
  {
    country: "South Africa",
    percentage: 2,
    content: "Decrease in agricultural productivity",
    currency: "ZAR",
    symbol: "R",
    rate: 17.48,
    mobileCode: 27,
    countryCode: "SAF",
  },
  {
    country: "Spain",
    percentage: 8.1,
    content: "Increase in average production",
    currency: "EUR",
    symbol: "€",
    rate: 0.91,
    mobileCode: 34,
    countryCode: "SPA",
  },
  {
    country: "Thailand",
    percentage: 0.5,
    content: "Increase in middle-aged labor",
    currency: "THB",
    symbol: "฿",
    rate: 33.27,
    mobileCode: 66,
    countryCode: "THA",
  },
  {
    country: "Togo",
    percentage: 40,
    content: "Increase in post-harvest loss",
    currency: "TGO",
    symbol: "Fr",
    rate: 591,
    mobileCode: 228,
    countryCode: "TOG",
  },
  {
    country: "Turkey",
    percentage: 2.7,
    content: "Increase in gross value",
    currency: "TRY",
    symbol: "₺",
    rate: 34.24,
    mobileCode: 90,
    countryCode: "TUR",
  },
  {
    country: "Ukraine",
    percentage: 10,
    content: "Increase in crop production",
    currency: "UAH",
    symbol: "₴",
    rate: 41.12,
    mobileCode: 380,
    countryCode: "UKR",
  },
  {
    country: "United Arab Emirates",
    percentage: 2.4,
    content: "Increase in crop production",
    currency: "AED",
    symbol: "د.إ",
    rate: 3.67,
    mobileCode: 971,
    countryCode: "UAE",
  },
  {
    country: "United Kingdom",
    percentage: 18.4,
    content: "Decrease in agricultural productivity",
    currency: "GBP",
    symbol: "£",
    rate: 0.76,
    mobileCode: 44,
    countryCode: "UKM",
  },
  {
    country: "United States",
    percentage: 1.5,
    content: "Increase in farm output",
    currency: "USD",
    symbol: "$",
    basicPrice: 15,
    premiumPrice: 80,
    rate: 1,
    mobileCode: 1,
    countryCode: "USA",
  },
];

const universalRate = data.find(
  (country) => country.country === "United States",
)?.basicPrice as any;
const premiumRate = data.find((country) => country.country === "United States")
  ?.premiumPrice as any;
data.forEach((country) => {
  if (country.rate && country.rate !== 0) {
    country.basicPrice = country.rate * universalRate;
  } else {
    console.log("Rate not available for country");
  }
});
data.forEach((country) => {
  if (country.rate && country.rate !== 0) {
    country.premiumPrice = country.rate * premiumRate;
  }
});
data.forEach((country) => {
  if (country.rate && country.country !== "United States") {
    country.price = [
      {
        name: "Wheat",
        price: [5.48, 5.43, 5.33, 5.1].map((price) => price * country.rate),
      },
      {
        name: "Rice",
        price: [14.68, 13.67, 13.35, 13.04].map(
          (price) => price * country.rate,
        ),
      },
      {
        name: "Soybeans",
        price: [13.46, 13.76, 12.66, 12.56].map(
          (price) => price * country.rate,
        ),
      },
      {
        name: "Sugar",
        price: [19.23, 19.26, 19.31, 19.32].map(
          (price) => price * country.rate,
        ),
      },
      {
        name: "Cotton",
        price: [24.74, 24.64, 24.96, 20.45].map(
          (price) => price * country.rate,
        ),
      },
      {
        name: "Maize",
        price: [4.29, 4.88, 4.6, 4.66].map((price) => price * country.rate),
      },
      {
        name: "Potato",
        price: [54.72, 51.84, 0, 0].map((price) => price * country.rate),
      },
    ];
  }
});
