tasks:
  - name: set-permissions
    init: |
      chmod -R 777 /workspace/data
    command: echo "Permissions set for /workspace/data"
  - name: docker-compose 
    init: docker-compose create
    command: docker-compose up -d
  - name: npm install
    init: npm install
    command:  export NEXTAUTH_URL="https://${CODESPACE_NAME}-3000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}/" && npm run dev
ports:
  - name: login
    port: 1025
    protocol: https